services:
  - type: web
    name: practicecover
    env: node
    rootDir: practicecover
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
